repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
    files: nixos/desktop/qtile/**/*.py
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
  - repo: local
    hooks:
      - id: statix-fix
        name: Statix Fix
        description: Fix files with statix
        entry: statix fix
        types: [nix]
        pass_filenames: false
        language: system
      - id: statix-check
        name: Statix Check
        description: Check files for improvements with statix
        entry: statix check
        types: [nix]
        pass_filenames: false
        language: system
