# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "ahci" "xhci_pci" "sd_mod" "sr_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = { 
    device = "/dev/nixos/root";
    fsType = "ext4";
  };

  fileSystems."/home" = { 
    device = "/dev/nixos/home";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" ={ 
   device = "/dev/disk/by-label/BOOT";
   fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/nixos/swap"; } ];

}
