#!/bin/bash

# Global variables
HOSTNAME=$(cat /etc/hostname)
MONITOR_COUNT=$(xrandr --query | awk '{if($2 == "connected"){print $1}}' | wc -l)
LAPTOP_NAME="wittano-laptop"
PC_NAME="wittano-pc"

# Functions
function is_run(){
  echo $(ps x | awk '{print $5}' | grep $1)
}

if [ -z $(is_run sxhkd) ]; then
  sxhkd &
fi

# Startup
wmname compiz &
nitrogen --restore &
qutebrowser &

if [ $HOSTNAME == 'wittano-laptop' ]; then
	xbacklight -set 50
fi

if [ -z $(is_run emacs) ];then
  emacs --daemon &
fi

if [ -z $(is_run syncthing) ] && [ -z $(command -v systemd) ]; then
  syncthing -no-browser &
fi

if [ -z $(is_run redshift) ]; then
	redshift -m randr -l 51.919438:19.145136 &
fi

# Polybar
if [ -z $(is_run polybar) ]; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    	if [ $HOSTNAME == $LAPTOP_NAME ]; then
    		MONITOR=$m polybar laptop &
    	else
      		MONITOR=$m polybar wittano &
    	fi
    done
fi

# BSPWM config
if [ $MONITOR_COUNT -gt 1 ]; then
  bspc monitor DVI-D-0 -d dev www sys virt mail game
  bspc monitor HDMI-0 -d chat www doc
else
  bspc monitor -d dev www sys virt mail game chat www doc
fi

bspc config border_width          2
bspc config window_gap            20
bspc config normal_border_color   "#212337"
bspc config focused_border_color  "#86E1FC"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

if [ $MONITOR_COUNT -gt 1 ]; then
  FIREFOX_WORKSPACE='^8'
  DISCORD_WORKSPACE='^7'
  PDF_WORKSPACE='^9'
else
  FIREFOX_WORKSPACE='^2'
  DISCORD_WORKSPACE='^7'
  PDF_WORKSPACE='^9'
fi

# Rules
bspc rule -a Emacs desktop='^1' state=fullscreen
bspc rule -a Terminator desktop='^3'
bspc rule -a jetbrains-idea desktop='^1'
bspc rule -a jetbrains-toolbox desktop='^1'
bspc rule -a discord desktop=$DISCORD_WORKSPACE
bspc rule -a "Rhythmbox" desktop='^4'
bspc rule -a Chromium desktop='^2'
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Firefox desktop=$FIREFOX_WORKSPACE
bspc rule -a Firefox-esr desktop=$FIREFOX_WORKSPACE
bspc rule -a Code desktop='^1'
bspc rule -a thunderbird desktop='^5'
bspc rule -a Thunderbird desktop='^5'
bspc rule -a Shortwave desktop='^4'
bspc rule -a "de.haeckerfelix.Shortwave" desktop='^4'
bspc rule -a Evince desktop=$PDF_WORKSPACE
bspc rule -a "Org.gnome.Nautilus" desktop='^3'
bspc rule -a "Tor Browser" desktop='^2'
bspc rule -a "jetbrains-webstorm" desktop='^1'
bspc rule -a "jetbrains-pycharm" desktop='^1'
bspc rule -a "Postman" desktop='^3'
bspc rule -a "Signal" desktop='^7'
bspc rule -a "Qmmp" desktop='^4'
bspc rule -a "player" desktop='^4'
bspc rule -a "Vivaldi-stable" desktop=$FIREFOX_WORKSPACE
bspc rule -a "Virt-manager" desktop='^4'
bspc rule -a "Boincmgr" desktop='^4'

# Games
bspc rule -a openttd desktop='^6'
bspc rule -a Steam desktop='^9'
bspc rule -a "lutris" desktop='^9'
bspc rule -a "genshinimpact.exe" desktop='^6'
bspc rule -a "steam_app_39540" desktop='^6' state=fullscreen
bspc rule -a "Paradox Launcher" desktop='^6'
bspc rule -a "Cities.x64" desktop='^6'
bspc rule -a "steam_app_813780" desktop='^6'
bspc rule -a "mb_warband_linux" desktop='^6'
bspc rule -a "hl2_linux" desktop='^6'
bspc rule -a "minecraft-launcher" desktop='^6'
bspc rule -a "Minecraft 1.17.1" desktop='^6'
