#!/bin/sh

# Keymap
sxhkd &

# Startup
wmname compiz &
redshift -m randr -l 51.919438:19.145136 &
# redshift &
# feh --bg-scale /usr/share/backgrounds/wallpaper-bspwm.jpg
nitrogen --restore &
emacs --daemon &
qutebrowser &
syncthing -no-browser &

MONITOR_COUNT=$(xrandr --query | grep 'connected' | cut -d " " -f1 | wc -l)
POLYBAR_ACTIVE=$(ps x | awk '{print $5}' | grep polybar)

# Polybar
if [ -z $POLYBAR_ACTIVE ]; then
  if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
      MONITOR=$m polybar wittano &
    done
  else
    polybar wittano &
  fi
fi

# BSPWM config
if [ $MONITOR_COUNT -gt 1 ]; then
  bspc monitor DVI-D-0 -d dev www sys music mail game
  bspc monitor HDMI-0 -d chat www doc
else
  bspc monitor -d dev www sys music mail virt chat doc
fi

bspc config border_width          2
bspc config window_gap            20
bspc config normal_border_color   "#212337"
bspc config focused_border_color  "#86E1FC"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# Rules
bspc rule -a Emacs desktop='^1' state=fullscreen
bspc rule -a Terminator desktop='^3'
bspc rule -a jetbrains-idea desktop='^1'
bspc rule -a discord desktop='^7'
bspc rule -a "Rhythmbox" desktop='^4'
bspc rule -a Chromium desktop='^2'
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Firefox desktop='^8'
bspc rule -a Firefox-esr desktop='^8'
bspc rule -a Code desktop='^1'
bspc rule -a thunderbird desktop='^5'
bspc rule -a Shortwave desktop='^4'
bspc rule -a "de.haeckerfelix.Shortwave" desktop='^4'
bspc rule -a Evince desktop='^9'
bspc rule -a "Org.gnome.Nautilus" desktop='^3'
bspc rule -a "Tor Browser" desktop='^2'
bspc rule -a "jetbrains-webstorm" desktop='^1'
bspc rule -a "jetbrains-pycharm" desktop='^1'
bspc rule -a "Postman" desktop='^3'


# Games
bspc rule -a openttd desktop='^6'
bspc rule -a Steam desktop='^6'
bspc rule -a "steam_app_39540" desktop='^6' state=fullscreen
bspc rule -a "Paradox Launcher" desktop='^6'
bspc rule -a "Cities.x64" desktop='^6'
bspc rule -a "steam_app_813780" desktop='^6'
bspc rule -a "mb_warband_linux" desktop='^6'
bspc rule -a "hl2_linux" desktop='^6'
