{ ... }: {
  imports =
    [
      ./alacritty.nix
      ./pomodoro.nix
      ./joplin.nix
      ./telegram.nix
      ./vivaldi.nix
      ./spotify.nix
      ./signal.nix
      ./discord.nix
      ./todoist.nix
      ./autostart.nix
      ./dunst.nix
      ./feh.nix
      ./fish.nix
      ./games.nix
      ./git.nix
      ./gtk.nix
      ./ide.nix
      ./kitty.nix
      ./lutris.nix
      ./neovim.nix
      ./nitrogen.nix
      ./picom.nix
      ./polybar.nix
      ./qt.nix
      ./ranger.nix
      ./redshift.nix
      ./rofi.nix
      ./tmux.nix
      ./stalonetray.nix
      ./thunderbird.nix
      ./qbittorrent.nix
      ./work.nix
      ./programming.nix
    ];
}
