# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    ./wacom.nix
    ./bootloader.nix
    ./nvidia.nix
    ./sound.nix
    ./virutalization.nix
  ];

  config = {
    boot = {
      initrd = {
        availableKernelModules = [ "ahci" "xhci_pci" "sd_mod" "sr_mod" ];
        kernelModules = [ ];
      };

      extraModulePackages = [ ];
    };

    hardware.trackpoint.emulateWheel = true;
  };

}
