# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot = {
    initrd = {
      availableKernelModules = [ "ahci" "xhci_pci" "sd_mod" "sr_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

    # Bootloader
    loader = {
      systemd-boot.enable = true;
      efi = {
        canTouchEfiVariables = true;
        efiSysMountPoint = "/boot/efi";
      };
      grub = {
        efiSupport = true;
        enable = true;
        version = 2;
        device = "nodev";
      };
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/nixos/root";
      fsType = "ext4";
    };
    "/home" = {
      device = "/dev/nixos/home";
      fsType = "ext4";
    };
    "/boot/efi" = {
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    };
    "/mnt/backup" = {
      device = "/dev/disk/by-uuid/f031287c-48e3-479e-8958-1986a02d0a8f";
      fsType = "ext4";
    };
  };

  # swapDevices = [{ device = "/dev/nixos/swap"; }];

  # Enable sound.
  sound.enable = true;

  virtualisation = {
    docker.enable = true;
    libvirtd.enable = true;
  };

  environment.systemPackages = with pkgs; [ virt-manager ];

  hardware = {
    trackpoint.emulateWheel = true;

    pulseaudio = {
      enable = true;
      support32Bit = config.hardware.pulseaudio.enable;
    };

    # OpenGL and Vulkan
    nvidia.modesetting.enable = true;
    opengl = {
      enable = true;
      driSupport = true;
      driSupport32Bit = true;
      setLdLibraryPath = true;
      extraPackages32 = with pkgs.pkgsi686Linux; [ libva ];
    };
  };

}
