name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v2
        with:
          pr-assignees: Wittano
          pr-title: "chore(flake): update flake.lock" 
          pr-labels: |                  
            dependencies
            automated
