name: Build Wittano nix repository
run-name: Build Wittano nix repository
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, edited, reopened, synchronize]
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        packages: [
            catppuccin-icon-theme,
            nixos-blur,
            dexy,
            sugar-candy,
            wings,
            bibata-cursor-theme,
            colloid-cursors-theme,
            patcherDir,
            rofiSwitchOff,
            gopher-nvim,
            nvim-comment,
            plenary-nvim,
            template-nvim,
            osu-lazer,
            osu-mime
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: "Install Nix"
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check flake lock diff
        id: flake-diff
        run: |
          DIFF=$(git diff HEAD~1 -- flake.lock)
          if [ -n $DIFF ]; then
            echo "raw-diff='1'" >> $GITHUB_OUTPUT
          else
            echo "raw-diff=''" >> $GITHUB_OUTPUT
          fi
      - name: "Install Cachix"
        uses: cachix/cachix-action@v14
        if: ${{ github.ref == 'refs/heads/main' && steps.flake-diff.outputs.raw-diff != '' }}
        with:
          name: wittano-nix-repo
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: "Build packages"
        if: ${{ steps.flake-diff.outputs.raw-diff != '' }}
        run: "nix build .#packages.x86_64-linux.${{ matrix.packages }}"
