name: build-nix-os
run-name: Build WittanoOS - NixOS edition
on: [push]
jobs:
  build:
    strategy_matrix:
      matrix:
        profile: [pc, pc-dev, virt, virt-dev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Nix"
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Install Cachix"
        uses: cachix/cachix-action@v11
        with:
          name: wittano-cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: "Check nix configurations"
        run: nix flake check
      - name: "Build configuration"
        run: "nix build .#nixosConfigurations.${{ matrix.profile }}.config.system.build.toplevel"