name: Build Wittano nix repository
run-name: Build Wittano nix repository
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, edited, reopened, synchronize]
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        packages: [
            catppuccin-icon-theme,
            nixos-blur,
            dexy,
            sugar-candy,
            wings,
            bibata-cursor-theme,
            colloid-cursors-theme,
            patcherDir,
            rofiSwitchOff,
            gopher-nvim,
            nvim-comment,
            plenary-nvim,
            template-nvim,
            osu-lazer,
            osu-mime
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install Nix"
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Install Cachix"
        uses: cachix/cachix-action@v14
        if: ${{ github.head_ref == 'main' }}
        with:
          name: wittano-nix-repo
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Get flake.nix diff 
        uses: GrantBirki/git-diff-action@v2.4.1
        id: flake-diff
        with:
          base_branch: "main"
          file_output_only: "true"
          search_path: ./flake.nix
      - name: "Build packages"
        if: ${{ steps.flake-diff.outputs.diff != '' }}
        run: "nix build .#packages.x86_64-linux.${{ matrix.packages }}"
