name: Build Wittano nix repository
run-name: Build Wittano nix repository
on:
  repository_dispatch:
    types: [create-pull-request]
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, edited, reopened, synchronize]
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        packages: [
            nixos-blur-playmouth,
            dexy,
            sugar-candy,
            wings,
            gopher-nvim,
            template-nvim,
            honkai-railway
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: "Install Nix"
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check flake lock diff
        id: flake-diff
        env:
          pkgName: ${{ matrix.packages }}
        run: |
          PKG_DIR=$(find ./pkgs -type d -iname $pkgName)
          if [ -n "$PKG_DIR" ]; then
            FILE_DIFF=$(git diff HEAD~1 -- $PKG_DIR)
          else
            FILE_DIFF=""
          fi

          DIFF=$(git diff HEAD~1 -- flake.lock)
          if [ -n "$DIFF" ] || [ -n "$FILE_DIFF" ]; then
            echo "raw-diff=1" >> $GITHUB_OUTPUT
          fi
      - name: "Install Cachix"
        uses: cachix/cachix-action@v14
        if: ${{ github.ref == 'refs/heads/main' && steps.flake-diff.outputs.raw-diff }}
        with:
          name: wittano-nix-repo
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: "Build packages"
        if: ${{ steps.flake-diff.outputs.raw-diff }}
        run: "nix build .#packages.x86_64-linux.${{ matrix.packages }}"
