name: update-flake
run-name: "Update flake and system"
on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Nix"
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Update flake"
        run: nix flake update
      - name: "Update repository"
        uses: EndBug/add-and-commit@v9
        with:
          add: flake.lock
          author_name: "Wittano"
          author_email: "radoslaw.ratyna@gmail.com"
          message: "chore(flake): update flake.lock"
