name: update-flake-lock
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: "0 0 * * 0"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update flake
        run: nix flake update
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Update flake.lock
        uses: ./.
  build:
    needs: lockfile
    strategy:
      matrix:
        packages: [
            nixos-blur-playmouth,
            dexy,
            suger-candy,
            wings,
            gopher-nvim,
            template-nvim,
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: "Install Nix"
        uses: cachix/install-nix-action@v2
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check flake lock diff
        id: flake-diff
        env:
          pkgName: ${{ matrix.packages }}
        run: |
          PKG_DIR=$(find ./pkgs -type d -iname $pkgName)
          if [ -n "$PKG_DIR" ]; then
            FILE_DIFF=$(git diff HEAD~1 -- $PKG_DIR)
          else
            FILE_DIFF=""
          fi

          DIFF=$(git diff HEAD~1 -- flake.lock)
          if [ -n "$DIFF" ] || [ -n "$FILE_DIFF" ]; then
            echo "raw-diff=1" >> $GITHUB_OUTPUT
          fi
      - name: "Install Cachix"
        uses: cachix/cachix-action@v14
        if: ${{ github.ref == 'refs/heads/main' && steps.flake-diff.outputs.raw-diff }}
        with:
          name: wittano-nix-repo
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: "Build packages"
        if: ${{ steps.flake-diff.outputs.raw-diff }}
        run: "nix build .#packages.x86_64-linux.${{ matrix.packages }}"
